// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\dao\user.go
//
// Generated by this command:
//
//	mockgen -source .\internal\repository\dao\user.go -package daomocks -destination .\internal\repository\dao\mocks\user.mock.gen.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	model "github.com/zhuguangfeng123/go-chat/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDao is a mock of UserDao interface.
type MockUserDao struct {
	ctrl     *gomock.Controller
	recorder *MockUserDaoMockRecorder
	isgomock struct{}
}

// MockUserDaoMockRecorder is the mock recorder for MockUserDao.
type MockUserDaoMockRecorder struct {
	mock *MockUserDao
}

// NewMockUserDao creates a new mock instance.
func NewMockUserDao(ctrl *gomock.Controller) *MockUserDao {
	mock := &MockUserDao{ctrl: ctrl}
	mock.recorder = &MockUserDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDao) EXPECT() *MockUserDaoMockRecorder {
	return m.recorder
}

// FindUserByPhone mocks base method.
func (m *MockUserDao) FindUserByPhone(ctx context.Context, phone string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByPhone", ctx, phone)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByPhone indicates an expected call of FindUserByPhone.
func (mr *MockUserDaoMockRecorder) FindUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByPhone", reflect.TypeOf((*MockUserDao)(nil).FindUserByPhone), ctx, phone)
}

// FindUserByUserId mocks base method.
func (m *MockUserDao) FindUserByUserId(ctx context.Context, userId string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUserId", ctx, userId)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUserId indicates an expected call of FindUserByUserId.
func (mr *MockUserDaoMockRecorder) FindUserByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUserId", reflect.TypeOf((*MockUserDao)(nil).FindUserByUserId), ctx, userId)
}

// FindUsersByUserIds mocks base method.
func (m *MockUserDao) FindUsersByUserIds(ctx context.Context, userIds []string) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByUserIds", ctx, userIds)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByUserIds indicates an expected call of FindUsersByUserIds.
func (mr *MockUserDaoMockRecorder) FindUsersByUserIds(ctx, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByUserIds", reflect.TypeOf((*MockUserDao)(nil).FindUsersByUserIds), ctx, userIds)
}

// InsertUser mocks base method.
func (m *MockUserDao) InsertUser(ctx context.Context, user model.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockUserDaoMockRecorder) InsertUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockUserDao)(nil).InsertUser), ctx, user)
}
