// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zhuguangfeng123/go-chat/cmd/server/app"
	"github.com/zhuguangfeng123/go-chat/internal/handler/jwt"
	user2 "github.com/zhuguangfeng123/go-chat/internal/handler/user"
	"github.com/zhuguangfeng123/go-chat/internal/repository"
	"github.com/zhuguangfeng123/go-chat/internal/repository/cache"
	"github.com/zhuguangfeng123/go-chat/internal/repository/dao"
	"github.com/zhuguangfeng123/go-chat/internal/service/code"
	"github.com/zhuguangfeng123/go-chat/internal/service/sms/ali"
	"github.com/zhuguangfeng123/go-chat/internal/service/user"
	"github.com/zhuguangfeng123/go-chat/ioc"
)

// Injectors from wire.go:

func InitWebServer() *app.App {
	cmdable := ioc.InitRedisCmd()
	jwtHandler := jwt.NewJwtHandler(cmdable)
	v := ioc.InitGinMiddleware(jwtHandler)
	db := ioc.InitMysql()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := user.NewUserService(userRepository)
	client := ioc.InitAliSmsClient()
	service := ali.NewAliService(client)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := code.NewCodeService(service, codeRepository)
	userHandler := user2.NewUserHandler(jwtHandler, userService, service, codeService)
	engine := ioc.InitWebServer(v, userHandler)
	appApp := &app.App{
		Server: engine,
	}
	return appApp
}
